### PR TITLE
Fix code errors in MyStorage.php

### LINKED ISSUE #758: Invalid code in MyStorage.php
## What Needs to be Documented?
The example code shows various warnings an errors in PHPstorm, like:

```
	public function getConnection() {
		if ($this->connection === null) {
			// do the connection to the storage lazily
			$this->connection = new \SomeVendor\FakeStorageLib\Connection($params);
		}
		return $this->connection;
	}
```
Undefined variable $params

```
	public function fopen($path, $mode) {
		switch ($mode) {
			case 'r':
			case 'rb':
				// this works if the library returns a PHP stream directly
				return $this->connection->getStream($path);
			case 'w':
			case 'w+':
			case 'wb':
			case 'wb+':
			case 'a':
			case 'ab':
			case 'r+':
			case 'a+':
			case 'x':
			case 'x+':
			case 'c':
			case 'c+':
				// most storages do not support on the fly stream upload for all modes,
				// so we use a temporary file first
				$ext = pathinfo($filename, PATHINFO_EXTENSION);
				$tmpFile = \OC::$server->getTempManager()->getTemporaryFile($ext);

				// this wrapper will call the callback whenever fclose() was called on the file,
				// after which we send the file to the library
				$result = CallbackWrapper::wrap(
					$source,
					null,
					null,
					function () use ($tmpFile, $path) {
						$this->connection->putFile($tmpFile, $path);
						unlink($tmpFile);
					}
				);
		}
		return false;
	}
```
Undefined variable $filename

```
	public function fopen($path, $mode) {
		switch ($mode) {
			case 'r':
			case 'rb':
				// this works if the library returns a PHP stream directly
				return $this->connection->getStream($path);
			case 'w':
			case 'w+':
			case 'wb':
			case 'wb+':
			case 'a':
			case 'ab':
			case 'r+':
			case 'a+':
			case 'x':
			case 'x+':
			case 'c':
			case 'c+':
				// most storages do not support on the fly stream upload for all modes,
				// so we use a temporary file first
				$ext = pathinfo($filename, PATHINFO_EXTENSION);
				$tmpFile = \OC::$server->getTempManager()->getTemporaryFile($ext);

				// this wrapper will call the callback whenever fclose() was called on the file,
				// after which we send the file to the library
				$result = CallbackWrapper::wrap(
					$source,
					null,
					null,
					function () use ($tmpFile, $path) {
						$this->connection->putFile($tmpFile, $path);
						unlink($tmpFile);
					}
				);
		}
		return false;
	}
```
Undefined variable $filename
Unused local variable $result

```
	public function touch($path, $time = null) {
		if ($time === null) {
			$time = time();
		}

		// many libraries might not support touch, so need to adapt
		if (!$this->file_exists($path)) {
			// create empty file
			$this->file_put_contents($path, '');
		}
		// set mtime to existing file
		return $this->connection->setModifiedTime($path, $time);
	}

	public function file_put_contents($path) {
		return $this->connection->setContents($path);
	}
```
Method call uses 2 parameters, but method signature uses 1 parameter - file_put_contents

Either:
a) fix the code to be a better example
or
b) delete the example if it is no longer relevant to anything

- [ ] also check other code examples to see if they are valid

## Where Does This Need To Be Documented?
`MyStorage.php` which will be in `modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php` after PR #756 

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #758.

### CODE REVIEW

**Comment by settermjd** [comment]
@phil-davis, the docs build pipeline doesn't do it at the moment, but I'd suggest the best thing to do is to run a linter over all the example code files.

File: modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php [hunk 1]
```diff
@@ -145,12 +145,12 @@ public function fopen($path, $mode) {
...
 				// so we use a temporary file first
-				$ext = pathinfo($filename, PATHINFO_EXTENSION);
+				$ext = pathinfo($path, PATHINFO_EXTENSION);
 				$tmpFile = \OC::$server->getTempManager()->getTemporaryFile($ext);
 
 				// this wrapper will call the callback whenever fclose() was called on the file,
 				// after which we send the file to the library
-				$result = CallbackWrapper::wrap(
+				return CallbackWrapper::wrap(
 					$source,
```
Comment (settermjd) [inline modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php]: @phil-davis, I still have to figure out where this is coming from.

**Comment by settermjd** [comment]
@phil-davis, there are make targets for linting XML, PHP, Yaml, Kotlin, Go, and JSON files, all starting with `validate-`.
